---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-connectivity-link-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Red Hat Connectivity Link Operator"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: connectivity-link-operator
  namespace: redhat-connectivity-link-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: redhat-connectivity-link-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: kuadrant-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
