---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-jobset-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "JobSet Operator"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: jobset-operator
  namespace: openshift-jobset-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - openshift-jobset-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: job-set
  namespace: openshift-jobset-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: tech-preview-v0.1
  name: job-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
