---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Red Hat OpenShift AI"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: rhods-operator
  channel: fast-3.x
  source: redhat-operators
  sourceNamespace: openshift-marketplace
