---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Tempo Operator"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tempo-operator
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo-product
  namespace: openshift-tempo-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: tempo-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
