kind: ConfigMap
apiVersion: v1
metadata:
  name: odh-segment-key-config
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/part-of: segment-io
    app.opendatahub.io/segment-io: "true"
data:
  segmentKeyEnabled: "false"
